package dev.fahim.livescanner.data

import android.content.Context
import android.util.Log
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString

/**
 * Bundled coastline geometry: for each airport, the polylines within ~90 NM of the field.
 * Points arrive as [lat, lon] pairs; inland fields are simply absent from the map.
 * Generated by tools/build_coastline.py from Natural Earth 1:10m data.
 */
@Serializable
data class CoastlineFile(
    val version: Int = 1,
    val airports: Map<String, List<List<List<Double>>>> = emptyMap(),
)

/** Coastline polylines near each airport, for the scope's geographic underlay. */
class Coastline(private val context: Context) {

    private val lock = Any()
    private var file: Map<String, List<List<List<Double>>>>? = null
    private val cache = HashMap<String, List<List<LatLng>>>()

    /** Polylines for [icao] as lists of points, or empty when the field is inland. */
    fun forAirport(icao: String): List<List<LatLng>> = synchronized(lock) {
        val key = icao.uppercase()
        cache[key] ?: decode(key).also { cache[key] = it }
    }

    private fun decode(icao: String): List<List<LatLng>> =
        load()[icao].orEmpty().mapNotNull { line ->
            line.mapNotNull { point ->
                if (point.size >= 2) LatLng(point[0], point[1]) else null
            }.takeIf { it.size >= 2 }
        }

    /** Parses the asset on first use; failures degrade to an empty underlay, never a crash. */
    private fun load(): Map<String, List<List<List<Double>>>> {
        file?.let { return it }
        val parsed = try {
            val text = context.assets.open(ASSET_NAME).bufferedReader().use { it.readText() }
            AppJson.decodeFromString<CoastlineFile>(text).airports
        } catch (t: Throwable) {
            Log.e(TAG, "Failed to load bundled coastline", t)
            emptyMap()
        }
        file = parsed
        return parsed
    }

    private companion object {
        const val ASSET_NAME = "coastline.json"
        const val TAG = "Coastline"
    }
}
