#!/usr/bin/env python3
"""Build the radar scope's aircraft silhouettes as Android VectorDrawables.

Targets on the scope are all the same diamond today. Colour already carries
altitude, so shape is free to carry what kind of aircraft it is — which is
information rather than decoration.

These are generated rather than drawn by hand or by an image model because the
requirements are geometric, and a generator can guarantee what matters:

  * perfect bilateral symmetry — only the right half is written out below, and
    the left is its mirror, so the two can never drift apart
  * nose at exactly 12 o'clock — the scope rotates each icon by the aircraft's
    track, and any other baseline puts every target on screen at a wrong angle
  * a single flat fill with no colour of its own, so android:tint can set it
    from the altitude ramp at draw time

Run --preview to rasterise each shape to the terminal. There is no way to open
a PNG in a build pipeline, and a silhouette that is secretly a blob is worth
catching before it ships.

Usage:
    python3 tools/build_aircraft_icons.py
    python3 tools/build_aircraft_icons.py --preview
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "app/src/main/res/drawable"

# Everything is described in a 100x100 box: x=50 is the centreline, y=0 is the
# nose end. Each entry lists the RIGHT half only, nose first, running aft.
SHAPES: dict[str, dict] = {
    "ic_ac_light": {
        "comment": "A1 light — high straight wing, short body. A Cessna from above.",
        "outline": [
            (50, 10), (54, 24), (54, 34),
            (92, 38), (92, 46), (54, 46),
            (53, 72),
            (70, 78), (70, 86), (53, 86),
            (51, 92),
        ],
    },
    "ic_ac_regional": {
        "comment": "A2 regional — longer body, slight sweep. A turboprop or small jet.",
        "outline": [
            (50, 7), (55, 20), (55, 36),
            (93, 48), (93, 57), (55, 57),
            (54, 76),
            (72, 83), (72, 91), (54, 91),
            (51, 95),
        ],
    },
    "ic_ac_narrowbody": {
        "comment": "A3 large — swept leading edge, 737/A320 proportions. The commonest target.",
        "outline": [
            (50, 5), (56, 19), (56, 35),
            (94, 54), (94, 63), (56, 63),
            (55, 79),
            (74, 87), (74, 95), (55, 95),
            (51, 97),
        ],
    },
    "ic_ac_widebody": {
        "comment": "A5 heavy — wider body, more span and sweep. A 777 from above.",
        "outline": [
            (50, 4), (59, 18), (59, 34),
            (97, 56), (97, 67), (59, 67),
            (58, 79),
            (79, 88), (79, 96), (58, 96),
            (52, 98),
        ],
    },
}

# The helicopter is not a winged aircraft and must not read as one. A fat pod on
# a thin boom gives it a different silhouette, and the rotor blades sit at 45
# degrees so they cannot be mistaken for wings — blades drawn along the axes
# merge with the fuselage and the whole thing turns into a plus sign.
ROTORCRAFT = {
    "comment": "A7 rotorcraft — pod, thin tail boom, and a rotor disc set off-axis.",
    "body": [
        (50, 24), (59, 31), (60, 43),
        (55, 50),
        (52, 54),
        (52, 78),
        (64, 83), (64, 91), (52, 91),
        (51, 95),
    ],
    "rotor_radius": 46.0,
    "blade_half_width": 2.6,
    "blade_angles_deg": (45.0, 135.0),
    "hub": (50.0, 50.0, 6.0),
}

def mirrored(outline: list[tuple[float, float]]) -> str:
    """One closed path: the given right half, then its mirror up the left side."""
    points = [f"M{outline[0][0]},{outline[0][1]}"]
    for x, y in outline[1:]:
        points.append(f"L{x},{y}")
    # Back up the left side, skipping the last point so the tail tip isn't doubled.
    for x, y in reversed(outline[:-1]):
        points.append(f"L{100 - x},{y}")
    points.append("Z")
    return " ".join(points)


def vector_xml(comment: str, paths: list[str]) -> str:
    body = "\n".join(
        f'    <path\n        android:fillColor="#FFFFFFFF"\n        android:pathData="{d}" />'
        for d in paths
    )
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- {comment}
     Generated by tools/build_aircraft_icons.py — edit that, not this.
     Nose points to 12 o'clock; the scope rotates it by the aircraft's track.
     Fill is plain white so android:tint can colour it from the altitude ramp. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="100"
    android:viewportHeight="100"
    android:tint="#FFFFFFFF">
{body}
</vector>
"""


def rotorcraft_paths() -> list[str]:
    """The pod and boom, plus two blades through the hub at 45 and 135 degrees."""
    import math

    cx, cy, hub_r = ROTORCRAFT["hub"]
    radius = ROTORCRAFT["rotor_radius"]
    half = ROTORCRAFT["blade_half_width"]

    paths = [mirrored(ROTORCRAFT["body"])]
    for degrees in ROTORCRAFT["blade_angles_deg"]:
        theta = math.radians(degrees)
        dx, dy = math.cos(theta), math.sin(theta)
        # Perpendicular, to give the blade its width.
        px, py = -dy, dx
        corners = [
            (cx + dx * radius + px * half, cy + dy * radius + py * half),
            (cx + dx * radius - px * half, cy + dy * radius - py * half),
            (cx - dx * radius - px * half, cy - dy * radius - py * half),
            (cx - dx * radius + px * half, cy - dy * radius + py * half),
        ]
        d = " ".join(
            f"{'M' if i == 0 else 'L'}{x:.1f},{y:.1f}" for i, (x, y) in enumerate(corners)
        )
        paths.append(d + " Z")

    paths.append(
        f"M{cx - hub_r},{cy} a{hub_r},{hub_r} 0 1,0 {2 * hub_r},0 "
        f"a{hub_r},{hub_r} 0 1,0 {-2 * hub_r},0 Z"
    )
    return paths


# ── Preview ──────────────────────────────────────────────────────────────────


def rasterise(paths: list[str], cols: int = 60, rows: int = 30) -> str:
    """Crude fill of the generated paths, so a wrong shape is visible here."""
    polys, rects, circles = [], [], []
    for d in paths:
        if " a" in d:  # the hub arc; approximate it as a circle
            cx, cy, r = ROTORCRAFT["hub"]
            circles.append((cx, cy, r))
            continue
        pts = []
        for token in d.replace("Z", "").split():
            if token[0] in "ML":
                x, y = token[1:].split(",")
                pts.append((float(x), float(y)))
        if len(pts) == 4:
            rects.append(pts)
        polys.append(pts)

    def inside(px: float, py: float, poly: list[tuple[float, float]]) -> bool:
        hit = False
        n = len(poly)
        for i in range(n):
            x1, y1 = poly[i]
            x2, y2 = poly[(i + 1) % n]
            if (y1 > py) != (y2 > py):
                xx = (x2 - x1) * (py - y1) / (y2 - y1) + x1
                if px < xx:
                    hit = not hit
        return hit

    lines = []
    for r in range(rows):
        py = (r + 0.5) * 100.0 / rows
        line = []
        for c in range(cols):
            px = (c + 0.5) * 100.0 / cols
            on = any(inside(px, py, poly) for poly in polys)
            on = on or any((px - cx) ** 2 + (py - cy) ** 2 <= rr * rr for cx, cy, rr in circles)
            line.append("##" [0] if on else " ")
        lines.append("".join(line))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--preview", action="store_true", help="rasterise to the terminal")
    parser.add_argument("--out", type=Path, default=OUT_DIR)
    args = parser.parse_args()

    built: dict[str, list[str]] = {
        name: [mirrored(spec["outline"])] for name, spec in SHAPES.items()
    }
    built["ic_ac_rotorcraft"] = rotorcraft_paths()
    comments = {name: spec["comment"] for name, spec in SHAPES.items()}
    comments["ic_ac_rotorcraft"] = ROTORCRAFT["comment"]

    if args.preview:
        for name, paths in built.items():
            print(f"\n=== {name} — {comments[name]}")
            print(rasterise(paths))
        return 0

    args.out.mkdir(parents=True, exist_ok=True)
    for name, paths in built.items():
        path = args.out / f"{name}.xml"
        path.write_text(vector_xml(comments[name], paths))
        print(f"  {path.relative_to(ROOT)}  ({path.stat().st_size} bytes)")
    print(f"\n{len(built)} silhouettes written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
